const APPS = [
    { id: 'settings', name: 'Settings', color: '#8e8e93', icon: 'fa-cog', area: 'grid', hyperIcon: 'hyperos_icon/system_settings.png', hyperColor: 'rgb(174,182,191)', colorIcon: 'coloros_icon/settings.png', colorColor: 'rgb(100,108,127)' },
    { id: 'music', name: 'Music', color: '#fa2d48', icon: 'fa-music', area: 'grid', hyperIcon: 'hyperos_icon/system_music.png', hyperColor: 'rgb(255,34,95)', colorIcon: 'coloros_icon/music.png', colorColor: 'rgb(220,40,53)' },
    { id: 'photos', name: 'Photos', color: '#fff', text: '#000', icon: 'fa-images', area: 'grid', hyperIcon: 'hyperos_icon/system_photos.png', hyperColor: 'rgb(255,255,255)', colorIcon: 'coloros_icon/gallery.png', colorColor: 'linear-gradient(to bottom, rgb(20,100,240), rgb(60,150,255))' },
    { id: 'clock', name: 'Clock', color: '#fff', text: '#000', icon: 'fa-clock', area: 'grid', border: false, hyperIcon: 'hyperos_icon/system_clock.png', hyperColor: 'rgb(174,182,191)', colorIcon: 'coloros_icon/clock.png', colorColor: 'linear-gradient(to bottom, rgb(249,249,249), rgb(248,248,248))' },
    { id: 'notes', name: 'Notes', color: '#f1c40f', icon: 'fa-sticky-note', area: 'grid', hyperIcon: 'hyperos_icon/system_notes.png', hyperColor: 'rgb(254,165,27)', colorIcon: 'coloros_icon/notes.png', colorColor: 'rgb(255,188,29)' },
    { id: 'calc', name: 'Calculator', color: '#000', icon: 'fa-calculator', area: 'grid', border: false, hyperIcon: 'hyperos_icon/system_calculator.png', hyperColor: 'linear-gradient(to bottom, rgb(255,255,255), rgb(255,255,255))', colorIcon: 'coloros_icon/calculator.png', colorColor: 'rgb(53,57,67)' },
    { id: 'files', name: 'Files', color: '#007aff', icon: 'fa-folder', area: 'grid', hyperIcon: 'hyperos_icon/system_filemanager.png', hyperColor: 'linear-gradient(to bottom, rgb(255,255,255), rgb(255,255,255))', colorIcon: 'coloros_icon/files.png', colorColor: 'linear-gradient(to bottom, rgb(250,250,250), rgb(248,248,248))' },
    { id: 'camera', name: 'Camera', color: '#333', icon: 'fa-camera', area: 'grid', hyperIcon: 'hyperos_icon/system_camera.png', hyperColor: 'rgb(174,182,191)', colorIcon: 'coloros_icon/camera.png', colorColor: 'rgb(215,216,225)' },
    { id: 'phone', name: 'Phone', color: '#34c759', icon: 'fa-phone', area: 'dock', hyperIcon: 'hyperos_icon/system_dialer.png', hyperColor: 'rgb(2,187,2)', colorIcon: 'coloros_icon/phone.png', colorColor: 'linear-gradient(to bottom, rgb(57,191,86), rgb(56,190,85), rgb(56,191,85), rgb(56,190,85), rgb(57,190,86))' },
    { id: 'messages', name: 'Messages', color: '#34c759', icon: 'fa-comment', area: 'dock', hyperIcon: 'hyperos_icon/system_messages.png', hyperColor: 'rgb(2,187,2)', colorIcon: 'coloros_icon/messages.png', colorColor: 'rgb(70,191,48)' },
    { id: 'safari', name: 'Browser', color: '#007aff', icon: 'fa-compass', area: 'dock', hyperIcon: 'hyperos_icon/system_browser.png', hyperColor: 'linear-gradient(to bottom, rgb(255,255,255), rgb(255,255,255))', colorIcon: 'coloros_icon/browser.png', colorColor: 'linear-gradient(to bottom, rgb(250,250,250), rgb(248,248,248))' },
    { id: 'mail', name: 'Mail', color: '#007aff', icon: 'fa-envelope', area: 'dock', hyperIcon: 'hyperos_icon/system_mail.png', hyperColor: 'rgb(0,116,254)', colorIcon: 'coloros_icon/mail.png', colorColor: 'rgb(18,102,242)' },
    { id: 'tiktok', name: 'TikTok', color: '#000000', icon: 'fa-video', area: 'grid', hyperIcon: 'global_icons/Tiktok.png', hyperColor: '#000000', colorIcon: 'global_icons/Tiktok.png', colorColor: '#000000' },
    { id: 'discord', name: 'Discord', color: '#5865f2', icon: 'fa-comment', area: 'grid', hyperIcon: 'global_icons/discord.png', hyperColor: '#5865f2', colorIcon: 'global_icons/discord.png', colorColor: '#5865f2' },
    { id: 'gmail', name: 'Gmail', color: '#fcfbfc', icon: 'fa-envelope', area: 'grid', hyperIcon: 'global_icons/gmail.png', hyperColor: '#fcfbfc', colorIcon: 'global_icons/gmail.png', colorColor: '#fcfbfc' },
    { id: 'playstore', name: 'Play Store', color: '#ffffff', icon: 'fa-play', area: 'grid', hyperIcon: 'global_icons/playstore.png', hyperColor: '#ffffff', colorIcon: 'global_icons/playstore.png', colorColor: '#ffffff' },
];
const State = {
    activeApp: null,
    isAnimating: false,
    darkMode: false,
    accentColor: '#007aff',
    islandMode: 'clock',
    islandColor: '#000',
    tapIndicators: false,
    brightness: 100,
    wallpapers: [
        'wallpapers/ColorOS/coloros15.jpg',
        'wallpapers/RealOS 3/wallpaper.png',
        'wallpapers/Oneplus/oneplus wallpaper.jpg',
        'wallpapers/Xiaomi/k80 wallpaper.jpg',
        'wallpapers/Xiaomi/k80 wallpaper2.jpg',
        'wallpapers/Xiaomi/k80 wallpaper3.jpg',
        'wallpapers/Xiaomi/k80 wallpaper 4.jpg',
        'wallpapers/Xiaomi/xiaomi 15 wallpaper.jpg',
        'wallpapers/Xiaomi/xiaomi blue.mp4',
        'wallpapers/Xiaomi/xiaomi orange.mp4',
        'wallpapers/Xiaomi/xiaomi purple.mp4',
        'wallpapers/Xiaomi/xiaomi ultra blue.png',
        'wallpapers/Xiaomi/xiaomi ultra green.png',
        'wallpapers/Xiaomi/xiaomi ultra orange.png',
        'wallpapers/Xiaomi/xiaomi ultra purple.png',
        'wallpapers/OriginOS/origin wallpaper dark.png',
        'wallpapers/OriginOS/origin wallpaper.png',
        'wallpapers/OriginOS/origin wallpaper2.png',
        'wallpapers/OriginOS/origin wallpaper3.png',
        'wallpapers/ColorOS/coloros15.jpg',
        'wallpapers/ColorOS/coloros15_1.jpg',
        'wallpapers/ColorOS/coloros15_2.jpg',
        'wallpapers/ColorOS/coloros15_3.jpg',
        'wallpapers/ColorOS/coloros15_4.jpg',
        'wallpapers/ColorOS/coloros15_breeze.jpg',
        'wallpapers/ColorOS/coloros15_breeze2.jpg',
        'wallpapers/ColorOS/coloros15_flower.jpg',
        'wallpapers/ColorOS/coloros15_flower2.jpg',
        'wallpapers/ColorOS/coloros15_flower3.jpg',
        'wallpapers/ColorOS/coloros15_flower4.jpg',
        'https://i.ibb.co/9HGWgS4w/wallpaper3.jpg',
        'https://i.ibb.co/FMtRmsm/wallpaper4.png',
        'https://i.ibb.co/ymJxLsYz/wallpaper5.png',
        'https://i.ibb.co/43v4xw9/wallpaper6.png'
    ],
    currentWall: 0,
    lockWall: 0,
    poweredOn: true,
    security: {
        pin: null,
        fingerprint: false,
        bioIcon: 'default'
    },
    aod: {
        enabled: false,
        image: null,
        style: 'default',
        text: '',
        wallpaper: false
    },
    notes: [],
    lsBlur: false,
    glassUI: true,
    locked: true,
    userProfile: {
        name: 'Guest',
        image: null
    },
    appShape: parseInt(localStorage.getItem('realos_v3_shape')) || 27,
    appSize: 64,
    iconPack: (localStorage.getItem('realos_v3_iconpack') === 'default' ? 'hyperos' : (localStorage.getItem('realos_v3_iconpack') || 'hyperos')),
    hasSetup: localStorage.getItem('realos_v3_setup') === 'true',
    animationSpeed: parseFloat(localStorage.getItem('realos_v3_animspeed') || '2.0'),
    themeColor: localStorage.getItem('realos_v3_theme') || '#ffffff',
    swipeToClose: true,
    homescreenBlur: localStorage.getItem('realos_v3_hs_blur') === 'true',
    blurBehindApps: localStorage.getItem('realos_v3_blur_behind') !== 'false',
    punchHole: localStorage.getItem('realos_v3_punch') === 'true',
    animStyle: localStorage.getItem('realos_v3_anim_style') || 'new',
    musicGradient: localStorage.getItem('realos_v3_music_grad') !== 'false',
    navStyle: localStorage.getItem('realos_v3_nav_style') || 'swipe',
    frameColor: localStorage.getItem('realos_v3_frame_color') || 'black',
    liteMode: localStorage.getItem('realos_v3_litemode') === 'true',
    specialEffects: localStorage.getItem('realos_v3_special') === 'true',
    devOptionsEnabled: localStorage.getItem('realos_v3_devoptions') === 'true',
    devWidth: parseInt(localStorage.getItem('realos_v3_devwidth')) || 400,
    devHeight: parseInt(localStorage.getItem('realos_v3_devheight')) || 860,
    showFps: localStorage.getItem('realos_v3_showfps') === 'true',
    iconPositions: {},
    animConfig: {
        openIconFade: 0.1,
        closeIconFade: 1.5,
        wallBlurDur: 0.12,
        closeShapeMorph: 0.34,
        openBezier: [0.2, 0.85, 0.1, 1],
        openScaleBezier: [0.2, 0.85, 0.1, 1],
        openScaleTime: 0.5,
        closeBezier: [0.15, 1.01, 0.3, 1.02],
        openAppZoomOut: 0.98,
        openWallZoom: 1.03,
        openWallBlur: true
    },
    clockConfig: {
        style: 'default',
        font: 'default',
        hourColor: '#ffffff',
        minuteColor: '#ffffff',
        autoColor: false,
        boldOpacity: 0.72,
        statusBarColor: false
    },
};
